routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

//Route::get('/', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('home');

Route::middleware('admin')->group(function (){

    Route::resource('category', 'CategoryController', [
        'except' => 'show'
    ]);

    Route::name ('orphans.')->prefix('orphans')->group(function () {
        Route::name ('index')->get ('/', 'AdminController@orphans');
        Route::name ('destroy')->delete ('/', 'AdminController@destroy');
    });

    Route::name ('maintenance.')->prefix('maintenance')->group(function () {
        Route::name ('index')->get ('/', 'AdminController@edit');
        Route::name ('update')->put ('/', 'AdminController@update');
    });

    Route::resource ('user', 'UserController', [
        'only' => ['index', 'edit', 'update', 'destroy']
    ]);

});

Route::middleware('auth', 'verified')->group(function () {

    Route::resource ('album', 'AlbumController', [
        'except' => 'show'
    ]);

    Route::name ('album')->get ('album/{slug}', 'ImageController@album');

   Route::resource ('image', 'ImageController', [
        'only' => ['create', 'store', 'destroy', 'update']
   ]);

    Route::name ('image.')->middleware ('ajax')->group (function () {
        Route::prefix('image')->group(function () {
            Route::name ('albums.update')->put ('{image}/albums', 'ImageController@albumsUpdate');
            Route::name ('description')->put ('{image}/description', 'ImageController@descriptionUpdate');
            Route::name ('adult')->put ('{image}/adult', 'ImageController@adultUpdate');
            Route::name('albums')->get('{image}/albums', 'ImageController@albums');
        });

        Route::name ('rating')->put ('rating/{image}', 'ImageController@rate');
    });

    Route::resource ('profile', 'ProfileController', [
        'only' => ['edit', 'update', 'destroy', 'show'],
        'parameters' => ['profile' => 'user']
    ]);

});

Route::name('category')->get('category/{slug}', 'ImageController@category');

Route::name ('user')->get ('user/{user}', 'ImageController@user');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Events\NameSaving;

class Category extends Model
{
    protected $fillable = [
        'name', 'slug',
    ];

    protected $dispatchesEvents = [
        'saving' => NameSaving::class,
    ];

    /**
     * Get the images
    */
    public function images()
    {
        return $this->hasMany(Image::class);
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use App\Repositories\CategoryRepository;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    public function __construct()
    {
        $this->middleware('ajax')->only('destroy');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\CategoryRequest  $request
     * @param  App\Http\Repositories\CategoryRepository  $repository
     *
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request, CategoryRepository $repository)
    {
        $repository->store($request->all());

        return redirect()->route('home')->with('ok', __('La catégorie a bien été enregistrée'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Category $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  CategoryRequest $request
     * @param  Category $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, Category $category)
    {
        $category->update($request->all());

        return redirect()->route('home')->with('ok', __('La catégorie a bien été modifiée'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Category $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();

        return response()->json();
    }
}

resources/views/categories/create.blade.php
@extends('layouts.form')

@section('card')

    @component('components.card')

        @slot('title')
            @lang('Ajouter une catégorie')
        @endslot

        <form method="POST" action="{{ route('category.store') }}">
            {{ csrf_field() }}

            @include('partials.form-group', [
                'title' => __('Nom'),
                'type' => 'text',
                'name' => 'name',
                'required' => true,
            ])

            @component('components.button')
                @lang('Envoyer')
            @endcomponent

        </form>

    @endcomponent

@endsection

resources/views/categories/edit.blade.php
@extends('layouts.form')
@section('card')
    @component('components.card')
        @slot('title')
            @lang('Modifier une catégorie')
        @endslot
        <form method="POST" action="{{ route('category.update', $category->id) }}">
            {{ csrf_field() }}
            {{ method_field('PUT') }}
            @include('partials.form-group', [
                'title' => __('Nom'),
                'type' => 'text',
                'name' => 'name',
                'value' => $category->name,
                'required' => true,
                ])
            @component('components.button')
                @lang('Envoyer')
            @endcomponent
        </form>
    @endcomponent
@endsection

resources/views/categories/index.blade.php
@extends('layouts.form')
@section('card')
    @component('components.card')
        @slot('title')
            @lang('Gestion des catégories')
        @endslot
        <table class="table table-dark text-white">
            <tbody>
            @foreach($categories as $category)
                <tr>
                    <td>{{ $category->name }}</td>
                    <td>
                        <a type="button" href="{{ route('category.destroy', $category->id) }}"
                           class="btn btn-danger btn-sm pull-right invisible" data-toggle="tooltip"
                           title="@lang('Supprimer la catégorie') {{ $category->name }}">
                            <i class="fas fa-trash fa-lg"></i></a>
                        <a type="button" href="{{ route('category.edit', $category->id) }}"
                           class="btn btn-warning btn-sm pull-right mr-2 invisible" data-toggle="tooltip"
                           title="@lang('Modifier la catégorie') {{ $category->name }}">
                            <i class="fas fa-edit fa-lg"></i></a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @endcomponent
@endsection
@section('script')
    <script>
        $(() => {
            $('a').removeClass('invisible')
        })
    </script>
    @include('partials.script-delete', ['text' => __('Vraiment supprimer cette catégorie ?'), 'return' => 'removeTr'])
@endsection